// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7OM_gXKcoDTVGJafRW9RiWOL9BkWjXdY',
    appId: '1:185236175269:web:38947155a087e6d6d2904c',
    messagingSenderId: '185236175269',
    projectId: 'darsbook-fdf81',
    authDomain: 'darsbook-fdf81.firebaseapp.com',
    storageBucket: 'darsbook-fdf81.firebasestorage.app',
    measurementId: 'G-3E9GSZ8PS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn4ECOZONRxJiUxr_91wISMyJshP7sopU',
    appId: '1:185236175269:android:9dd97b0610a567c3d2904c',
    messagingSenderId: '185236175269',
    projectId: 'darsbook-fdf81',
    storageBucket: 'darsbook-fdf81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBKj9D_cBdrY5u-ZUjze6hfQ1b1XQlSgs',
    appId: '1:185236175269:ios:3ee5bd6d744ba88fd2904c',
    messagingSenderId: '185236175269',
    projectId: 'darsbook-fdf81',
    storageBucket: 'darsbook-fdf81.firebasestorage.app',
    iosBundleId: 'com.example.darsBook',
  );
}
